spring:
  application:
    name: notifcation-service
  config:
    import: "optional:file:.env[.properties]"
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${HOST_EMAIL}    # Thay bằng email của bạn
    password: ${HOST_APPLICATION_PASSWORD}    # Thay bằng App Password ở bước 2 (viết liền không khoảng trắng)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 9090