server:
    port: 9090

spring:
    application:
        name: notifcation-service

    config:
        import: "optional:file:.env[.properties]"
    
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_APP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
                    ssl:
                        trust: smtp.gmail.com
